version: "3.6"
services:

  builder:
    build: .
    volumes:
      - ./wine:/wine
      - x11socket:/tmp/.X11-unix/
    environment: 
      DISPLAY: ":0"
      WINEDLLOVERRIDES: "mscoree=d;mshtml=d"
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    # ref: https://github.com/osrf/docker_images/issues/21#issuecomment-239334515
    ipc: host

  xserver:
    build: ./xserver
    ports: 
      - 5900:5900
    volumes: 
      - x11socket:/tmp/.X11-unix/

volumes:
  x11socket:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m
